FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.sln .
COPY ActiveAdviceWeb/*.csproj ./ActiveAdviceWeb/

COPY Logger/*.csproj ./Logger/

COPY ActiveAdviceTests/*.csproj ./ActiveAdviceTests/
COPY CacheFramework/*.csproj ./CacheFramework/
COPY MailComponent/*.csproj ./MailComponent/
COPY DataLayer/*.csproj ./DataLayer/
COPY ActiveAdviceWebAPI/*.csproj ./ActiveAdviceWebAPI/
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "ActiveAdviceWeb.dll"]
